### ISSUE TITLE
Bug in sketch list

### ISSUE THREAD

**Issue by esteinig** [esteinig/sketchy#31]
Bug in `pathlib.Path` file name parsing when using `path.name` where the file name starts with an `s` that is remove, for example 

```
Path('test/saureus.msh').name
```

returns

```
"aureus.msh"
```

Fixing with `os.path.basename`

**Comment by mbhall88** [comment]
Hang on. This doesn't sound right. Are you sure there is not something upstream causing this?  
When I run that code in my local python3.6 shell I get the following:
```py
>>> from pathlib import Path
>>> Path('test/saureus.msh').name
'saureus.msh'
```

**Comment by esteinig** [comment]
Uh oh must be then. I'll check it out, it was super weird.

**Comment by esteinig** [comment]
There is a reference to it in the `sketchy.storage.FoogleCloudSketch.list_sketches` method which before switching to `os.path.basename`:

```python
for f in Path(dir_path).glob("*.msh"):
    name, kmer_size, sketch_size = f.name.split("_")
```

**Comment by mbhall88** [comment]
Is there a way of getting the file list in `dir_path` when you ran this and got the error?

**Comment by esteinig** [comment]
hey i think it's a bug related to this - see my correction above where in fact did a `f.name.strip('.msh')` was done before the split.

it actually persists in a replicable example:

```python
from pathlib import Path

test_case = Path("saureus/saureus_15_1000.msh")
assert(test_case.name.strip(".msh") == "aureus_15_1000")
```

**Comment by esteinig** [comment]
can you see if you can replicate that?

**Comment by esteinig** [comment]
Ah it's in the strip behavior:

```
from pathlib import Path

test_case_1 = Path("saureus/saureus_15_1000.msh")
assert(test_case_1.name.lstrip(".msh") == "aureus_15_1000")
assert(test_case_1.name.rstrip(".msh") == "saureus_15_1000")
```

**Comment by esteinig** [comment]
Correcting it to `rstrip`

**Comment by esteinig** [comment]
Also didn't know this was the default behavior:

```python
from pathlib import Path

test_case_1 = Path("saureus/haureus_15_1000.msh")
assert(test_case_1.name.lstrip(".msh") == "aureus_15_1000")
```

**Comment by esteinig** [comment]
Ah and here is the explanation on the strip method, my apologies:

> The chars argument is not a prefix; rather, all combinations of its values are stripped

**Comment by mbhall88** [comment]
Yes, I was going to say, according to [the docs](https://docs.python.org/3.7/library/stdtypes.html#str.strip) any chars you give to `strip()` will be removed.

I think there are a couple of other functions which are more like what you want here. See the examples below.

```py
from pathlib import Path

expected = "saureus_15_1000"

test_case_1 = Path("saureus/saureus_15_1000.msh")
actual = test_case_1.with_suffix("").name
assert actual == expected

def rreplace(s: str, old: str, new: str, count: int = 1) -> str:
    return new.join(s.rsplit(old, count))

actual = rreplace(test_case_1.name, ".msh", "")
assert actual == expected

```

**Comment by esteinig** [comment]
Yes! I was looking for the standard use of `with_suffix` - my bad
