### ISSUE TITLE
Conda distribution

### ISSUE THREAD

**Issue by esteinig** [esteinig/sketchy#33]
@mbhall88 is there any chance you might have a quick look at the `meta.yaml` and `build.sh`. i can't for my life figure out what's going wrong when building, it can't find the `sketchy` module.

**Comment by mbhall88** [comment]
I'll take a look tomorrow (UK time)

**Comment by esteinig** [comment]
thanks, i will take a look later as well.

**Comment by esteinig** [comment]
Package builds fine during build stage:

![sketchy_build](https://user-images.githubusercontent.com/12873366/75298197-96a87480-587d-11ea-8dfb-400c7a140a8f.JPG)

but fails in test stage both to import  module (shown here) and run terminal client that's setup in `setup.py`

![test_fail](https://user-images.githubusercontent.com/12873366/75298243-ac1d9e80-587d-11ea-9461-169225571723.JPG)

**Comment by esteinig** [comment]
`conda build -c bioconda -c conda-forge -c esteinig .` in root directory

**Comment by mbhall88** [comment]
Ok, I get a different error.

```
Compiling sketchy-rs v0.4.0 (/home/vagrant/miniconda/conda-bld/sketchy_1582712481709/work)
    Finished release [optimized] target(s) in 1m 14s
mv: cannot stat 'target/release/sketchy': No such file or directory
Traceback (most recent call last):
  File "/home/vagrant/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/vagrant/miniconda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 469, in main
    execute(sys.argv[1:])
  File "/home/vagrant/miniconda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 460, in execute
    verify=args.verify, variants=args.variants)
  File "/home/vagrant/miniconda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/vagrant/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 2344, in build_tree
    notest=notest,
  File "/home/vagrant/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 1492, in build
    cwd=src_dir, stats=build_stats)
  File "/home/vagrant/miniconda/lib/python3.7/site-packages/conda_build/utils.py", line 398, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/vagrant/miniconda/lib/python3.7/site-packages/conda_build/utils.py", line 378, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/vagrant/miniconda/conda-bld/sketchy_1582712481709/work/conda_build.sh']' returned non-zero exit status 1.

```

**Comment by mbhall88** [comment]
I don't normally build conda packages locally like this. I normally build them as though I am [packaging them for bioconda](https://bioconda.github.io/contributor/workflow.html).

**Comment by esteinig** [comment]
thanks for the pointer! i'll have a go at it

**Comment by mbhall88** [comment]
It requires a tarball from a github release, but it builds and tests everything inside a docker container (the one that is used for building on bioconda).  

I am still having the same import errors you are getting trying to do it locally...

**Comment by mbhall88** [comment]
Are you planning on adding `pf-core` to conda? You won't be able to build on [bioconda until it exists in a "standard" channel](https://bioconda.github.io/contributor/guidelines.html#dependencies).

**Comment by esteinig** [comment]
I'm going to pull over the few components from `pf-core` and remove it from the dependencies, it will be easier to manage this way. Parsing the `pf-core` survey pipeline output should be native.

**Comment by mbhall88** [comment]
Ok. Let me know when that is done and I will have another go.

**Comment by esteinig** [comment]
thanks man give it a shot now, removed the dependency in `v0.4.3`

**Comment by mbhall88** [comment]
Question. Do you use interactive PyQt plotting with matplotlib? If note we can just use `matplotlib-base`. See https://bioconda.github.io/contributor/linting.html#uses-matplotlib for details

**Comment by esteinig** [comment]
Great suggestion, I didn't know about `matplotlib-base`

**Comment by mbhall88** [comment]
Unfortunately, I had to pin the version of python to 3.7 to satisfy the `pyfastx` dependency.

**Comment by esteinig** [comment]
Thanks so much mate - looks like it is working! Closing this issue.
