### ISSUE TITLE
Sketch dereplication

### ISSUE THREAD

**Issue by esteinig** [esteinig/sketchy#37]
Dereplicate overrepresented sequence and genotypes in sketches.

**Comment by esteinig** [comment]
Use @rrwick [dereplication script](https://github.com/rrwick/Assembly-Dereplicator) for the overrepresented sequence types in the *S. aureus* reference sketch.

I wonder if we need to check for genotype representation so all unique ones are captured by the dereplication? Or set the threshold in the network construction so that all unique genotypes are covered.

**Comment by dn-ra** [comment]
Just posting our slack conversation here so we can refer back to it:

> Dan:

>  Good news man. Ryan's dereplicator took the saureus genomes down to 105
> 4:10
> from 38981!
> 4:10
> But it doesn't look like it outputs outputs a tree of the dereplication or anything
> 4:11
> I'd like to modify it to do that so that once it maps to a dreplicated node we can load all of those genomes into memory and complete the full analysis
> 4:11
> what do you think?
> 4:17 PM
> Is that even necessary? I guess it depends on the variants within  each clade

> Eike  6:39 PM
> ah so that's not gonna work, my apologies
> 6:40
> we can try though but we'd have to tune down the --ranks parameter to 2, to compare only the top two predictions, otherwise the summary evaluation will compute over the entire window and if only one genome per sequence type is available then it's going to compute nonsense.
> 6:43
> is there any chance we can find a medium and target something like at least 20 genomes per sequence type / genotype within sequence type? the full spectrum of unique genotypes must be preserved within each sequence type at least because that's where the algorithm finds neighbors, and have a few representatives so we don't have to tune down --ranks too much, so that we still get the benefit of the consensus evaluation over the ranks. minhash is a bit fuzzy so we need it, and the evaluation sssh scores also aggregate the genotypes across the ranks, s can't go too low!
> 6:43
> in representation
> 6:44
> sorry that it's a bit more convoluted, but thanks so much for doing this :)

> Dan  9:50 AM
> If we take the top 20 genomes from each cluster will that work?
> 9:51
> I feel like it's gonna be hard to replicate the full database analysis i with dereplication if it needs the find those neighbours
> 9:53
> Orrr we could dereplicate at different thresholds. and have 120 different clusters (low threshold) with a set of dereplicated genomes (high threshold) behind them

**Comment by esteinig** [comment]
hey thanks for reminding me. yes, i think we can try different thresholds and maybe write small script to see how it affects the number of unique genotypes per MLST - if it depletes those too much we can increase threshold to include more genomes. 

i have already included a prototype mapping approach to visualize the neighbor hits on a tree or population graph. i'll try and figure out how to do that better, at the moment the `.gif` production is in an `R` script.

**Comment by esteinig** [comment]
hey @dn-ra if you get the chance to look at the databases, i think we have to remove singular sequence types and those where n < 5 - 10 perhaps? i'm thinking we need a minimum number of representative genomes for the consensus window through `--ranks` for the feature aggregation in evaluation as we talked about.

**Comment by esteinig** [comment]
Closing using dereplicate script from Ryan in v0.5.0
