### ISSUE TITLE
sklearn dependecy not listed

### ISSUE THREAD

**Issue by mbhall88** [esteinig/sketchy#52]
It looks like https://github.com/esteinig/sketchy/commit/38e3f3d2c34741798493b877220d2d9d71828fb3 introduced `sklearn`? This doesn't seem to be in the requirements.txt file and is also breaking the conda build (https://github.com/bioconda/bioconda-recipes/pull/28691)

**Comment by esteinig** [comment]
Thanks man, have rewritten the code base, will come back to this for the new version and fix the recipe if needed
