### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by colindaven** [esteinig/sketchy#54]
This link 
https://sketchy.github.io/docs
is unreachable.

ta

**Comment by esteinig** [comment]
Thanks! I'm in the process of restructuring this whole thing - new link to the (unfinished) documentation added:

https://esteinig.github.io/sketchy

**Comment by esteinig** [comment]
Would wait to try `Sketchy` for a couple of weeks until the latest version is ready. We have been working on a preprint that's about to be finished and which outlines some of the drawbacks of this method. Will close now, but feel free to open again if you have any questions!
